### ISSUE TITLE
Manganelo Source Bugs 

### ISSUE THREAD

**Issue by ConradWeiser** [Paperback-iOS/extensions#13]
Manganelo does not pass it's "Retrieve Home Page Sections" test case, never getting a proper response back from the server.

```
 Manganelo Tests
    √ Retrieve Manga Details (1104ms)
    √ Get Chapters (1337ms)
    √ Get Chapter Details (2245ms)
    √ Searching for Manga With Valid Tags (471ms)
    √ Searching for Manga With Invalid Tags (453ms)
    1) Retrieve Home Page Sections

 1) Manganelo Tests
       Retrieve Home Page Sections:
     AssertionError: No response from server: expected [] not to be empty
      at Suite.<anonymous> (f:\Development\extensions\src\tests\Manganelo.test.ts:84:58)
      at Generator.next (<anonymous>)
      at fulfilled (f:\Development\extensions\src\tests\Manganelo.test.ts:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

It also doesn't pass the test case handling determining whether a manga has been updated or not. The current implementation of this test case is likely bad, as you can never guarantee that a manga has had an update in X amount of time. 30 days is hardcoded. This should likely be removed or redesigned, but this is a test case issue.

**Comment by ConradWeiser** [comment]
This has since been resolved
